
common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *common
  database: aj2_development
  username: postgres
  password: '123'

test:
  <<: *common
  database: aj2_test
  username: postgres
  password: '123'

production:
  <<: *common
  database: aj2_production
  username: postgres
  password: '123'
